// Copyright 2024 The MathWorks, Inc.

export const SET_OVERLAY_VISIBILITY = 'SET_OVERLAY_VISIBILITY';
export const REQUEST_SERVER_STATUS = 'REQUEST_SERVER_STATUS';
export const RECEIVE_SERVER_STATUS = 'RECEIVE_SERVER_STATUS';
export const REQUEST_SET_LICENSING = 'REQUEST_SET_LICENSING';
export const REQUEST_UPDATE_LICENSING = 'REQUEST_UPDATE_LICENSING';
export const REQUEST_STOP_MATLAB = 'REQUEST_STOP_MATLAB';
export const REQUEST_START_MATLAB = 'REQUEST_START_MATLAB';
export const RECEIVE_SET_LICENSING = 'RECEIVE_SET_LICENSING';
export const RECEIVE_UPDATE_LICENSING = 'RECEIVE_UPDATE_LICENSING';
export const RECEIVE_STOP_MATLAB = 'RECEIVE_STOP_MATLAB';
export const RECEIVE_START_MATLAB = 'RECEIVE_START_MATLAB';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const REQUEST_ENV_CONFIG = 'REQUEST_ENV_CONFIG';
export const RECEIVE_ENV_CONFIG = 'RECEIVE_ENV_CONFIG';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';