# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  # Triggers the workflow on push events for the "main" branch
  push:
    branches: [ "main" ]

  # Triggers the workflow on pull requests for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  typescript-build-and-test:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [windows-latest, ubuntu-latest, macos-13]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm clean install
      run: npm ci
    - name: Build
      run: npm run compile
    - name: Run TypeScript Unit Tests
      run: npm test

  matlab-test:
    name: ${{ matrix.matlab-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        matlab-version: [R2021b, R2022a, R2022b, latest]
        os: [windows-latest, ubuntu-latest, macos-13]
    steps:
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2.2.0
    - name: Run MATLAB Unit Tests
      uses: matlab-actions/run-tests@v2.1.1
